server:
  port : 8020


spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/sky?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references : true

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:
          - com.sky.controller
          - com.sky.entity
# knife4j的增强配置，不需要增强可以不配

knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis :
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package : com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true